<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('surahs')->delete();

        $surahs = [
            ['id' => 1, 'nama_surah' => 'Al-Fatihah', 'jumlah_ayat' => 7],
            ['id' => 2, 'nama_surah' => 'Al-Baqarah', 'jumlah_ayat' => 286],
            ['id' => 3, 'nama_surah' => 'Ali \'Imran', 'jumlah_ayat' => 200],
            ['id' => 4, 'nama_surah' => 'An-Nisa', 'jumlah_ayat' => 176],
            ['id' => 5, 'nama_surah' => 'Al-Ma\'idah', 'jumlah_ayat' => 120],
            ['id' => 6, 'nama_surah' => 'Al-An\'am', 'jumlah_ayat' => 165],
            ['id' => 7, 'nama_surah' => 'Al-A\'raf', 'jumlah_ayat' => 206],
            ['id' => 8, 'nama_surah' => 'Al-Anfal', 'jumlah_ayat' => 75],
            ['id' => 9, 'nama_surah' => 'At-Taubah', 'jumlah_ayat' => 129],
            ['id' => 10, 'nama_surah' => 'Yunus', 'jumlah_ayat' => 109],
            ['id' => 11, 'nama_surah' => 'Hud', 'jumlah_ayat' => 123],
            ['id' => 12, 'nama_surah' => 'Yusuf', 'jumlah_ayat' => 111],
            ['id' => 13, 'nama_surah' => 'Ar-Ra\'d', 'jumlah_ayat' => 43],
            ['id' => 14, 'nama_surah' => 'Ibrahim', 'jumlah_ayat' => 52],
            ['id' => 15, 'nama_surah' => 'Al-Hijr', 'jumlah_ayat' => 99],
            ['id' => 16, 'nama_surah' => 'An-Nahl', 'jumlah_ayat' => 128],
            ['id' => 17, 'nama_surah' => 'Al-Isra', 'jumlah_ayat' => 111],
            ['id' => 18, 'nama_surah' => 'Al-Kahf', 'jumlah_ayat' => 110],
            ['id' => 19, 'nama_surah' => 'Maryam', 'jumlah_ayat' => 98],
            ['id' => 20, 'nama_surah' => 'Taha', 'jumlah_ayat' => 135],
            ['id' => 21, 'nama_surah' => 'Al-Anbiya', 'jumlah_ayat' => 112],
            ['id' => 22, 'nama_surah' => 'Al-Hajj', 'jumlah_ayat' => 78],
            ['id' => 23, 'nama_surah' => 'Al-Mu\'minun', 'jumlah_ayat' => 118],
            ['id' => 24, 'nama_surah' => 'An-Nur', 'jumlah_ayat' => 64],
            ['id' => 25, 'nama_surah' => 'Al-Furqan', 'jumlah_ayat' => 77],
            ['id' => 26, 'nama_surah' => 'Asy-Syu\'ara', 'jumlah_ayat' => 227],
            ['id' => 27, 'nama_surah' => 'An-Naml', 'jumlah_ayat' => 93],
            ['id' => 28, 'nama_surah' => 'Al-Qasas', 'jumlah_ayat' => 88],
            ['id' => 29, 'nama_surah' => 'Al-\'Ankabut', 'jumlah_ayat' => 69],
            ['id' => 30, 'nama_surah' => 'Ar-Rum', 'jumlah_ayat' => 60],
            ['id' => 31, 'nama_surah' => 'Luqman', 'jumlah_ayat' => 34],
            ['id' => 32, 'nama_surah' => 'As-Sajdah', 'jumlah_ayat' => 30],
            ['id' => 33, 'nama_surah' => 'Al-Ahzab', 'jumlah_ayat' => 73],
            ['id' => 34, 'nama_surah' => 'Saba', 'jumlah_ayat' => 54],
            ['id' => 35, 'nama_surah' => 'Fatir', 'jumlah_ayat' => 45],
            ['id' => 36, 'nama_surah' => 'Ya-Sin', 'jumlah_ayat' => 83],
            ['id' => 37, 'nama_surah' => 'As-Saffat', 'jumlah_ayat' => 182],
            ['id' => 38, 'nama_surah' => 'Sad', 'jumlah_ayat' => 88],
            ['id' => 39, 'nama_surah' => 'Az-Zumar', 'jumlah_ayat' => 75],
            ['id' => 40, 'nama_surah' => 'Ghafir', 'jumlah_ayat' => 85],
            ['id' => 41, 'nama_surah' => 'Fussilat', 'jumlah_ayat' => 54],
            ['id' => 42, 'nama_surah' => 'Asy-Syura', 'jumlah_ayat' => 53],
            ['id' => 43, 'nama_surah' => 'Az-Zukhruf', 'jumlah_ayat' => 89],
            ['id' => 44, 'nama_surah' => 'Ad-Dukhan', 'jumlah_ayat' => 59],
            ['id' => 45, 'nama_surah' => 'Al-Jasiyah', 'jumlah_ayat' => 37],
            ['id' => 46, 'nama_surah' => 'Al-Ahqaf', 'jumlah_ayat' => 35],
            ['id' => 47, 'nama_surah' => 'Muhammad', 'jumlah_ayat' => 38],
            ['id' => 48, 'nama_surah' => 'Al-Fath', 'jumlah_ayat' => 29],
            ['id' => 49, 'nama_surah' => 'Al-Hujurat', 'jumlah_ayat' => 18],
            ['id' => 50, 'nama_surah' => 'Qaf', 'jumlah_ayat' => 45],
            ['id' => 51, 'nama_surah' => 'Az-Zariyat', 'jumlah_ayat' => 60],
            ['id' => 52, 'nama_surah' => 'At-Tur', 'jumlah_ayat' => 49],
            ['id' => 53, 'nama_surah' => 'An-Najm', 'jumlah_ayat' => 62],
            ['id' => 54, 'nama_surah' => 'Al-Qamar', 'jumlah_ayat' => 55],
            ['id' => 55, 'nama_surah' => 'Ar-Rahman', 'jumlah_ayat' => 78],
            ['id' => 56, 'nama_surah' => 'Al-Waqi\'ah', 'jumlah_ayat' => 96],
            ['id' => 57, 'nama_surah' => 'Al-Hadid', 'jumlah_ayat' => 29],
            ['id' => 58, 'nama_surah' => 'Al-Mujadilah', 'jumlah_ayat' => 22],
            ['id' => 59, 'nama_surah' => 'Al-Hasyr', 'jumlah_ayat' => 24],
            ['id' => 60, 'nama_surah' => 'Al-Mumtahanah', 'jumlah_ayat' => 13],
            ['id' => 61, 'nama_surah' => 'As-Saff', 'jumlah_ayat' => 14],
            ['id' => 62, 'nama_surah' => 'Al-Jumu\'ah', 'jumlah_ayat' => 11],
            ['id' => 63, 'nama_surah' => 'Al-Munafiqun', 'jumlah_ayat' => 11],
            ['id' => 64, 'nama_surah' => 'At-Tagabun', 'jumlah_ayat' => 18],
            ['id' => 65, 'nama_surah' => 'At-Talaq', 'jumlah_ayat' => 12],
            ['id' => 66, 'nama_surah' => 'At-Tahrim', 'jumlah_ayat' => 12],
            ['id' => 67, 'nama_surah' => 'Al-Mulk', 'jumlah_ayat' => 30],
            ['id' => 68, 'nama_surah' => 'Al-Qalam', 'jumlah_ayat' => 52],
            ['id' => 69, 'nama_surah' => 'Al-Haqqah', 'jumlah_ayat' => 52],
            ['id' => 70, 'nama_surah' => 'Al-Ma\'arij', 'jumlah_ayat' => 44],
            ['id' => 71, 'nama_surah' => 'Nuh', 'jumlah_ayat' => 28],
            ['id' => 72, 'nama_surah' => 'Al-Jinn', 'jumlah_ayat' => 28],
            ['id' => 73, 'nama_surah' => 'Al-Muzzammil', 'jumlah_ayat' => 20],
            ['id' => 74, 'nama_surah' => 'Al-Muddassir', 'jumlah_ayat' => 56],
            ['id' => 75, 'nama_surah' => 'Al-Qiyamah', 'jumlah_ayat' => 40],
            ['id' => 76, 'nama_surah' => 'Al-Insan', 'jumlah_ayat' => 31],
            ['id' => 77, 'nama_surah' => 'Al-Mursalat', 'jumlah_ayat' => 50],
            ['id' => 78, 'nama_surah' => 'An-Naba', 'jumlah_ayat' => 40],
            ['id' => 79, 'nama_surah' => 'An-Nazi\'at', 'jumlah_ayat' => 46],
            ['id' => 80, 'nama_surah' => '\'Abasa', 'jumlah_ayat' => 42],
            ['id' => 81, 'nama_surah' => 'At-Takwir', 'jumlah_ayat' => 29],
            ['id' => 82, 'nama_surah' => 'Al-Infitar', 'jumlah_ayat' => 19],
            ['id' => 83, 'nama_surah' => 'Al-Mutaffifin', 'jumlah_ayat' => 36],
            ['id' => 84, 'nama_surah' => 'Al-Insyiqaq', 'jumlah_ayat' => 25],
            ['id' => 85, 'nama_surah' => 'Al-Buruj', 'jumlah_ayat' => 22],
            ['id' => 86, 'nama_surah' => 'At-Tariq', 'jumlah_ayat' => 17],
            ['id' => 87, 'nama_surah' => 'Al-A\'la', 'jumlah_ayat' => 19],
            ['id' => 88, 'nama_surah' => 'Al-Gasyiyah', 'jumlah_ayat' => 26],
            ['id' => 89, 'nama_surah' => 'Al-Fajr', 'jumlah_ayat' => 30],
            ['id' => 90, 'nama_surah' => 'Al-Balad', 'jumlah_ayat' => 20],
            ['id' => 91, 'nama_surah' => 'Asy-Syams', 'jumlah_ayat' => 15],
            ['id' => 92, 'nama_surah' => 'Al-Lail', 'jumlah_ayat' => 21],
            ['id' => 93, 'nama_surah' => 'Ad-Duha', 'jumlah_ayat' => 11],
            ['id' => 94, 'nama_surah' => 'Asy-Syarh', 'jumlah_ayat' => 8],
            ['id' => 95, 'nama_surah' => 'At-Tin', 'jumlah_ayat' => 8],
            ['id' => 96, 'nama_surah' => 'Al-\'Alaq', 'jumlah_ayat' => 19],
            ['id' => 97, 'nama_surah' => 'Al-Qadr', 'jumlah_ayat' => 5],
            ['id' => 98, 'nama_surah' => 'Al-Bayyinah', 'jumlah_ayat' => 8],
            ['id' => 99, 'nama_surah' => 'Az-Zalzalah', 'jumlah_ayat' => 8],
            ['id' => 100, 'nama_surah' => 'Al-\'Adiyat', 'jumlah_ayat' => 11],
            ['id' => 101, 'nama_surah' => 'Al-Qari\'ah', 'jumlah_ayat' => 11],
            ['id' => 102, 'nama_surah' => 'At-Takasur', 'jumlah_ayat' => 8],
            ['id' => 103, 'nama_surah' => 'Al-\'Asr', 'jumlah_ayat' => 3],
            ['id' => 104, 'nama_surah' => 'Al-Humazah', 'jumlah_ayat' => 9],
            ['id' => 105, 'nama_surah' => 'Al-Fil', 'jumlah_ayat' => 5],
            ['id' => 106, 'nama_surah' => 'Quraisy', 'jumlah_ayat' => 4],
            ['id' => 107, 'nama_surah' => 'Al-Ma\'un', 'jumlah_ayat' => 7],
            ['id' => 108, 'nama_surah' => 'Al-Kausar', 'jumlah_ayat' => 3],
            ['id' => 109, 'nama_surah' => 'Al-Kafirun', 'jumlah_ayat' => 6],
            ['id' => 110, 'nama_surah' => 'An-Nasr', 'jumlah_ayat' => 3],
            ['id' => 111, 'nama_surah' => 'Al-Masad', 'jumlah_ayat' => 5],
            ['id' => 112, 'nama_surah' => 'Al-Ikhlas', 'jumlah_ayat' => 4],
            ['id' => 113, 'nama_surah' => 'Al-Falaq', 'jumlah_ayat' => 5],
            ['id' => 114, 'nama_surah' => 'An-Nas', 'jumlah_ayat' => 6],
        ];

        DB::table('surahs')->insert($surahs);
    }
}
